/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paquete;
import java.awt.*;
import java.awt.event.*;
import java.awt.Robot;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.event.InputEvent;
/**
 *
 * @author Esther
 */
public class Unlock extends javax.swing.JFrame {

    /**
     * Creates new form Unlock
     */
    public Unlock() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("DESBLOQUEO DE PANTALLA ");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("La aplicación tomará control de su maquina");
        jLabel3.setMaximumSize(new java.awt.Dimension(31, 14));
        jLabel3.setMinimumSize(new java.awt.Dimension(31, 14));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Advertencia!!!");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Conecte su dispositivo movil ANDROID");
        jLabel6.setMaximumSize(new java.awt.Dimension(31, 14));
        jLabel6.setMinimumSize(new java.awt.Dimension(31, 14));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        jLabel2.setText("Está deacuerdo con el acceso al control de su maquina ");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/8.png"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(512, 512));
        jLabel7.setMinimumSize(new java.awt.Dimension(512, 512));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(520, 520, 520))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // activa la clase Ejecutar al seleccionar el botón aceptar
            ejecutar();
        //En caso de error ingresa al catch 
        } catch (AWTException ex) {       
             //Se muestra el error de AWTException 
            Logger.getLogger(Unlock.class.getName()).log(Level.SEVERE, null, ex);
        } 
         //En caso de error ingresa al catch 
        catch (InterruptedException ex) {
            //Se muestra el error datos recibidos 
            Logger.getLogger(Unlock.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public static void ejecutar() throws AWTException, InterruptedException{
    
     Runtime app = Runtime.getRuntime(); 
        try{ 
        //    se ejecuta el programa NOTEpad para mostrar el mensaje de control
        app.exec("\"C:\\Program Files\\Notepad++\\notepad++.exe\""); 
                // inicializamos una cadena de caracteres que se almacena en Teclado
                // se ira escribiendo: HOLA EMPEZAMOS LA EJECUCION
                int teclas[]={KeyEvent.VK_H, KeyEvent.VK_O,
                              KeyEvent.VK_L, KeyEvent.VK_A,
                              KeyEvent.VK_SPACE, KeyEvent.VK_E,
                              KeyEvent.VK_M, KeyEvent.VK_P,
                              KeyEvent.VK_E, KeyEvent.VK_Z,
                              KeyEvent.VK_A, KeyEvent.VK_M,
                              KeyEvent.VK_O, KeyEvent.VK_S,
                              KeyEvent.VK_SPACE,KeyEvent.VK_L, 
                              KeyEvent.VK_A, KeyEvent.VK_SPACE,
                              KeyEvent.VK_E, KeyEvent.VK_J,
                              KeyEvent.VK_E, KeyEvent.VK_C,
                              KeyEvent.VK_U, KeyEvent.VK_C,
                              KeyEvent.VK_I, KeyEvent.VK_O,
                              KeyEvent.VK_N};
                //inicializamos la libreir Robot para tomar control del equipo
                Robot r=new Robot();
                //Ejecutamos la estructura repetitiva para empezar el typeo               
                for(int x=0;x<teclas.length;x++){
                    //desactivamos el robot 1000 milisegundos
                    r.delay(1000);
                    //Se presiona la tecla de la cadea teclado
                    r.keyPress(teclas[x]);
                    //Se deja de presionar la tecla de la cadena teclado
                    r.keyRelease(teclas[x]);
                }
                //En caso de que todo se ejecute de manera correcta se ejecuta el try
            try{    
                //Se ejecuta el programa dr.Fone
                app.exec("\"C:\\Program Files (x86)\\iSkysoft\\dr.fone - Screen Unlock (Android) (IS)\\DrFoneToolKit.exe\"");
                //se realiza la llamada a la libreria Robot
                Robot bot = new Robot();  
                //FUNCION ROBOT EN EL MOUSE
                //-----------------------------
                //Posicionamos el mouse (x,y);
                bot.mouseMove(300, 300);
                //dormimos el robot por 10000 mili segundos
                bot.delay(10000);
                // BUTTON1_MASK simula clic derecho 
                bot.mousePress(InputEvent.BUTTON1_MASK);
                // BUTTON1_MASK simula unclic derecho 
                bot.mouseRelease(InputEvent.BUTTON1_MASK); 
                // -------------------------------------- 
                //Ubicación en el Menú de Desbloqueo de Pantalla
                bot.mouseMove(450, 500);
                //dormimos el robot por 50000 mili segundos
                bot.delay(5000); 
                 
                // -----------------------------------------                
                bot.delay(900);  
                bot.mouseMove(273, 749);  
                // BUTTON1_MASK simula clic derecho  
                bot.mousePress(InputEvent.BUTTON1_MASK);
                // BUTTON1_MASK simula unclic derecho 
                bot.mouseRelease(InputEvent.BUTTON1_MASK);
                bot.delay(57000);
                //-------------------------------------------
                //Se ejecuta la aplicación
                app.exec("\"C:\\Program Files (x86)\\iSkysoft\\dr.fone - Screen Unlock (Android) (IS)\\DrFoneToolKit.exe\"");
                //----------------------
                bot.delay(1000); 
                bot.mouseMove(300, 200);
                bot.delay(1000);
                bot.mouseMove(400, 200); 
                bot.delay(100);  
                //bot.mousePress(InputEvent.BUTTON1_MASK);
                //bot.mouseRelease(InputEvent.BUTTON1_MASK);
              
                r.keyPress(KeyEvent.VK_WINDOWS);
                r.keyPress(KeyEvent.VK_D);
                bot.delay(100);
                r.keyRelease(KeyEvent.VK_WINDOWS);
                r.keyRelease(KeyEvent.VK_D);
                bot.delay(100);
                bot.mouseMove(563, 700); 
                
                
            }
            catch(IOException e){
            }
      
        }
        //"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"
        catch(IOException e){
            System.out.println(e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Unlock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Unlock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Unlock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Unlock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Unlock().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
